{{ 
    exports.publishOn = new Date().toString()
}}


POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6ImVsaWZAZG9lLmNvbSIsImlhdCI6MTcyNjY2MTM1MSwiZXhwIjoxNzI2NjY0OTUxLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.eNz4PlRNb8i6y_p-z10eKHEYPrK3ZWstMrU5V0tlLbc
{
  "title": "Post with new createpost dto45543",
  "postType": "post",
  "slug": "a-s-d-f-s-s-dd",
  "status": "published",
  "content": "This is the content.",
  "schema": "{\"type\":\"object\"}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn":"{{publishOn}}",

  "metaOptions": {
    "metaValue": "{\"cascade\": true, \"cascade\":true}"
  },
  "tags":[1,5]
  
}
