POST http://localhost:8000/users/
Content-Type: application/json
{
  "firstName":"john",
  "lastName":"doe",
  "email":"john3@doe.com",
  "password":"Password123#"
}


POST http://localhost:8000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6ImVsaWZAZG9lLmNvbSIsImlhdCI6MTcyNjA3MjI1NiwiZXhwIjoxNzI2MDc1ODU2LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.GXEp_4-yEQ1cR0A6V7pltg4Cvz4MVokOa_y1RuyQC68
{
  "users": [
            {
            "firstName":"aaaa",
            "lastName":"aaa",
            "email":"aaa@doe.com",
            "password":"Passwodd123#"
            },
            {
            "firstName":"bbb",
            "lastName":"bbb",
            "email":"bbbb@gmail.com",
            "password":"Passwodd123#"
            }

          ]
}



