POST http://localhost:8000/users/
Content-Type: application/json
{
  "firstName":"john",
  "lastName":"doe",
  "email":"john3@doe.com",
  "password":"Password123#"
}


POST http://localhost:8000/users/create-many
Content-Type: application/json
{
  "users": [
            {
            "firstName":"aaaa",
            "lastName":"aaa",
            "email":"aaa@doe.com",
            "password":"Passwodd123#"
            },
            {
            "firstName":"bbb",
            "lastName":"bbb",
            "email":"bbbb@gmail.com",
            "password":"Passwodd123#"
            }

          ]
}



